#!/usr/bin/env python3
"""Prep the Interview-at-scale webcam clip.

Turns any recording of someone answering on camera into the two things the
scene needs, both cut to the same window so they stay in sync:

  media/interview-clip.mp4   square, muted, 240px, H.264 with keyframes every
                             0.5s (seek-friendly for scrubbing)
  src/ListenClip.tsx         the clip's loudness, one value per 30ms (the dot
                             grid's column rate), which drives the visualizer

Usage:
  python3 scripts/prep-interview-clip.py video/answer.mov
  python3 scripts/prep-interview-clip.py video/answer.mov --start 1.2 --end 7.8
  python3 scripts/prep-interview-clip.py --placeholder   # synthetic stand-in

The recording beat in the scene lasts exactly as long as the trimmed clip.
Needs ffmpeg on PATH.
"""
import argparse, math, os, random, re, struct, subprocess, sys, tempfile, wave

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_MP4 = os.path.join(ROOT, "media", "interview-clip.mp4")
OUT_TS = os.path.join(ROOT, "src", "ListenClip.tsx")
FRAME_MS = 30
SR = 44100


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"ffmpeg failed:\n{' '.join(cmd)}\n{r.stderr[-2000:]}")
    return r


def make_placeholder(path):
    """A speech-like voice (syllable bursts, phrase gaps) and a waveform that
    moves with it — enough to prove the video/visualizer sync end to end."""
    random.seed(7)
    dur = 6.0
    n = int(dur * SR)
    env = [0.0] * n
    t = 0.38
    while t < dur - 0.3:
        for _ in range(random.randint(3, 9)):
            d = 0.09 + random.random() * 0.13
            amp = 0.45 + random.random() * 0.55
            a, b = int(t * SR), int((t + d) * SR)
            for i in range(a, min(n, b + int(0.25 * SR))):
                dt = (i - a) / SR
                e = (1 - math.exp(-dt / 0.012)) if i < b else math.exp(-(i - b) / SR / 0.11)
                env[i] = max(env[i], amp * e)
            t += d + 0.02 + random.random() * 0.045
            if t > dur - 0.3:
                break
        t += 0.3 + random.random() * 0.35
    wav = os.path.join(os.path.dirname(path), "placeholder.wav")
    with wave.open(wav, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR)
        frames = bytearray()
        for i in range(n):
            f0 = 140 + 18 * math.sin(i / SR * 3.1)
            ph = 2 * math.pi * f0 * i / SR
            s = sum(math.sin(ph * h) / h for h in (1, 2, 3, 4, 5))
            frames += struct.pack("<h", int(max(-1, min(1, 0.45 * env[i] * s)) * 32767))
        w.writeframes(bytes(frames))
    run([
        "ffmpeg", "-y", "-f", "lavfi", "-i", f"color=c=0xE3DCCE:s=480x480:r=30:d={dur}", "-i", wav,
        "-filter_complex",
        "[1:a]showwaves=s=400x240:mode=cline:rate=30:colors=0x0021CC:scale=sqrt:draw=full[w];[0:v][w]overlay=40:120[v]",
        "-map", "[v]", "-map", "1:a", "-shortest", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", path,
    ])


def levels(src, start, end):
    """RMS per 30ms window in dB, mapped to 0..1 between the clip's quiet
    floor and its loud peaks."""
    trim = (["-ss", str(start)] if start else []) + (["-to", str(end)] if end else [])
    r = run([
        "ffmpeg", *trim, "-i", src, "-vn", "-ac", "1", "-ar", str(SR), "-af",
        f"asetnsamples=n={SR * FRAME_MS // 1000}:p=0,astats=metadata=1:reset=1,"
        "ametadata=print:key=lavfi.astats.Overall.RMS_level:file=-",
        "-f", "null", "-",
    ])
    db = [float(m) if m not in ("-inf", "inf", "nan") else -120.0
          for m in re.findall(r"RMS_level=(\S+)", r.stdout)]
    if not db:
        sys.exit("no audio found in the clip")
    s = sorted(db)
    floor = max(-70.0, s[int(len(s) * 0.15)] + 6)   # room tone + margin
    peak = max(floor + 12, s[min(len(s) - 1, int(len(s) * 0.98))])
    return [max(0.0, min(1.0, (d - floor) / (peak - floor))) ** 1.2 for d in db]


def encode(src, start, end):
    os.makedirs(os.path.dirname(OUT_MP4), exist_ok=True)
    trim = (["-ss", str(start)] if start else []) + (["-to", str(end)] if end else [])
    run([
        "ffmpeg", "-y", *trim, "-i", src, "-an",
        "-vf", "crop='min(iw,ih)':'min(iw,ih)',scale=240:240,fps=30",
        "-c:v", "libx264", "-profile:v", "main", "-pix_fmt", "yuv420p", "-crf", "26",
        "-g", "15", "-movflags", "+faststart", OUT_MP4,
    ])


def write_ts(lv, placeholder):
    packed = "".join(f"{min(99, round(v * 99)):02d}" for v in lv)
    body = f'''// ListenClip — the Interview-at-scale webcam clip and its loudness track.
// GENERATED by scripts/prep-interview-clip.py — rerun it with a new recording
// instead of editing by hand. `src` is relative to the site root; in Framer,
// upload media/interview-clip.mp4 as an asset and paste its URL here.
export const INTERVIEW_CLIP = {{
  src: "media/interview-clip.mp4",
  placeholder: {"true" if placeholder else "false"},
  frameMs: {FRAME_MS},
  durationMs: {len(lv) * FRAME_MS},
  /** loudness per frame, two digits each (00–99) */
  levels: "{packed}",
}}
'''
    with open(OUT_TS, "w") as f:
        f.write(body)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", nargs="?")
    ap.add_argument("--start", type=float, default=0)
    ap.add_argument("--end", type=float, default=0)
    ap.add_argument("--placeholder", action="store_true")
    a = ap.parse_args()
    with tempfile.TemporaryDirectory() as tmp:
        src = a.input
        if a.placeholder:
            src = os.path.join(tmp, "placeholder.mov")
            make_placeholder(src)
        if not src:
            ap.error("pass a recording, or --placeholder")
        lv = levels(src, a.start, a.end)
        encode(src, a.start, a.end)
        write_ts(lv, a.placeholder)
    kb = os.path.getsize(OUT_MP4) // 1024
    print(f"wrote {os.path.relpath(OUT_MP4, ROOT)} ({kb} KB) and {os.path.relpath(OUT_TS, ROOT)} "
          f"({len(lv)} frames, {len(lv) * FRAME_MS / 1000:.2f}s)")


if __name__ == "__main__":
    main()
